# Retail Store Sales

### What are we trying to Find?
Through this dataset of retail store, we would perform cleaning of data which is priortise over any process before jumping to find queries for business insights. Therefore, the workflow of this project starts from Python Library - Pandas, for easy and smart cleaning of data.

### Setting up the Library

In [2]:
import numpy as np
import pandas as pd

store = pd.read_csv('retail_store_sales.csv')

### About the File
1. Tranaction_ID
2. Customer_ID
3. Category
4. Item
5. Price Per Unit
6. Quantity
7. Total Spent
8. Payment Method
9. Location
10. Transaction Date
11. Discount Applied

### Data Cleaning and Detail about Dataset

In [3]:
store.describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [ ]:
store.isna().sum()   #Sum of null values

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [ ]:
store.duplicated().sum()   #sum of duplicated values

np.int64(0)

In [ ]:
store.shape   #Given in (Rows, Columns)

(12575, 11)

In [ ]:
store.info()  #To check column along with non-null count and Data Type

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  str
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(1), str(7)
memory usage: 1.1+ MB

In [ ]:
store.nunique()  #Types of unique values in a given dataset

Transaction ID      12575
Customer ID            25
Category                8
Item                  200
Price Per Unit         25
Quantity               10
Total Spent           227
Payment Method          3
Location                2
Transaction Date     1114
Discount Applied        2
dtype: int64

In [ ]:
store.dropna(inplace=True)   #Delete the missing values

In [ ]:
store['Transaction Date'] = pd.to_datetime(store['Transaction Date'])   #Convert String to Date format in Transaction ID Column

In [ ]:
store.drop_duplicates()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN

In [ ]:
store.fillna({'Price Per Unit':45}, inplace=True)  #Fill missing values of column(Price per unit) = 45, if any missing values exist

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,2023-06-10,True
...,...,...,...,...,...,...,...,...,...,...,...
12566,TXN_6298574,CUST_01,Milk Products,Item_1_MILK,5.0,4.0,20.0,Cash,Online,2023-05-09,False
12567,TXN_4890318,CUST_25,Butchers,Item_3_BUT,8.0,5.0,40.0,Credit Card,In-store,2023-03-28,False
12569,TXN_2318174,CUST_18,Patisserie,Item_1_PAT,5.0,9.0,45.0,Digital Wallet,In-store,2024-05-13,False
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True

In [ ]:
store.replace('Digital Wallet', 'Online/UPI', inplace=True) 
store.replace('Credit Card', 'Debit/Credit', inplace=True) #Replacing the name

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Online/UPI,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Online/UPI,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Debit/Credit,Online,2022-10-05,False
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Online/UPI,Online,2022-10-02,False
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Debit/Credit,In-store,2023-06-10,True
...,...,...,...,...,...,...,...,...,...,...,...
12566,TXN_6298574,CUST_01,Milk Products,Item_1_MILK,5.0,4.0,20.0,Cash,Online,2023-05-09,False
12567,TXN_4890318,CUST_25,Butchers,Item_3_BUT,8.0,5.0,40.0,Debit/Credit,In-store,2023-03-28,False
12569,TXN_2318174,CUST_18,Patisserie,Item_1_PAT,5.0,9.0,45.0,Online/UPI,In-store,2024-05-13,False
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True

In [ ]:
store.to_csv('cleaned_dataset', index = True)  #Saving the file format in local device